services:
    app.apiauthenticationsubscriber:
        class: AppBundle\EventSubscriber\ApiAuthenticationSubscriber
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }