services:
    app.apiauthenticationsubscriber:
        class: AppBundle\EventSubscriber\ApiAuthenticationSubscriber
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
